version: '3.8'
services:
  db:
     image: mysql:8.0
     container_name: mysql-db
     environment:
       MYSQL_ROOT_PASSWORD: springboot
       MYSQL_DATABASE: mall

     ports:
       - "3307:3306"
     volumes:
       - mysql-data:/var/lib/mysql


  app:
      build: .
      container_name: spring-boot-app
      ports:
        - "8080:8080"
      environment:
        DB_URL: jdbc:mysql://host.docker.internal:3307/mall?serverTimezone=Asia/Taipei&characterEncoding=utf-8
        DB_USER: root
        DB_PASS: springboot
      depends_on:
        - db


volumes:
    mysql-data: